name: Commit Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
        env:
          GH_TOKEN_CUSTOM: ${{ secrets.GH_TOKEN_CUSTOM }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

      - name: Save seen commits
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          # STEP 1: sync repo FIRST
          git fetch origin main
          git reset --hard origin/main

          # STEP 2: run bot already modified seen.json
          git add seen.json

          # STEP 3: commit only if changes exist
          git commit -m "Update seen commits" || exit 0

          # STEP 4: push safely
          git push origin main